### ISSUE TITLE
Gettin Required parser 'WebURL' from parser groupRequired parser 'WebURL' from parser group 'WebURL' did not produce result!

### ISSUE THREAD

**Issue by premkumarmsc** [blinkinput/blinkinput-ios#27]
Hi, In my app i am using PPRegexOcrParserFactory for URL regex. but i am getting 

Required parser 'WebURL' from parser group 'WebURL' did not produce result!

static NSString *ID_URL = @"WebURL";

////////////////////////
 NSString *urlRegEx =
    @"(http|https)://((\\w)*|([0-9]*)|([-|_])*)+([\\.|/]((\\w)*|([0-9]*)|([-|_])*))+";
    
PPRegexOcrParserFactory *urlParser = [[PPRegexOcrParserFactory alloc] initWithRegex:urlRegEx];
  
 [ocrRecognizerSettings addOcrParser:urlParser name:ID_URL group:ID_URL];
    
   
    [settings.scanSettings addRecognizerSettings:ocrRecognizerSettings];

/////////////////////////////

 if ([result isKindOfClass:[PPBlinkOcrRecognizerResult class]]) {
            PPBlinkOcrRecognizerResult* ocrRecognizerResult = (PPBlinkOcrRecognizerResult*)result;
            
            
            NSString *message = [ocrRecognizerResult parsedResultForName:ID_URL parserGroup:ID_URL];
            
            NSLog(@"Result:%@",message);

**Comment by cularj** [comment]
Hi @premkumarmsc,

you are getting that message because the scanned text doesn't match the regex,
you need to make sure that the regex you are using matches your text. 

Since you are trying to scan URL, this might be a better regex:
`@"(http|https)://((\\w)*|([0-9]*)|([-|_])*)+([\\.|/]((\\w)*|([0-9]*)|([-|_])*))+"`

Kind regards,
Jure
