### ISSUE TITLE
Type 'ViewController' does not conform to protocol 'PPScanningDelegate'

### ISSUE THREAD

**Issue by YogeshBharate** [blinkinput/blinkinput-ios#41]
I have integrated the BlinkID in my application and I have already implemented the following mandatory methods:

- func scanningViewControllerUnauthorizedCamera(_ scanningViewController: UIViewController) {}

- func scanningViewController(_ scanningViewController: UIViewController, didFindError error: Error) {}
- func scanningViewControllerDidClose(_ scanningViewController: UIViewController) {}
- func scanningViewController(_ scanningViewController: UIViewController?, didOutputMetadata metadata: PPMetadata) {}
- func scanningViewController(_ scanningViewController: UIViewController?, didOutputResults results: [PPRecognizerResult]){}

Still I am facing the error **"Type 'ViewController' does not conform to protocol 'PPScanningDelegate' Error"** and **Type 'ViewController' does not conform to protocol 'PPScanningDelegate'**.

In my another app still its working fine, but when I start to integrate in new app, it gives me above error.

Is there any extra setting or framework required to resolve this issue.

**Type 'ViewController' does not conform to protocol 'PPScanningDelegate'** for this error when we add protocol stubs? Its add following three methods 

- func scanningViewControllerUnauthorizedCamera(_ scanningViewController: UIViewController & PPScanningViewController) {}
- func scanningViewController(_ scanningViewController: UIViewController & PPScanningViewController, didFindError error: Error) {}
- func scanningViewControllerDidClose(_ scanningViewController: UIViewController & PPScanningViewController) {}

Thanks in advance ,please let me know how to resolve this issue. Why this issue occures ?

**Comment by jcular** [comment]
Hi @YogeshBharate,

sorry for delayed response.
This happens because the framework is written in objective-c, swift headers are automatically generated from objective-c. Since they are automatically generated and as Swift versions change so the automatically generated stubs that xcode creates. Your older project probably uses older version of Swift than the one you created recently, protocol funcs in swift were different in that version than the one you have now. This is normal and you can trust xcode to create the correct stubs for you. You can see the difference is in `UIViewController & PPScanningViewController`, this just means `scanningViewController` is a `UIViewController` that implements protocol `PPScanningViewController `.

Kind regards,
Jure

**Comment by YogeshBharate** [comment]
@jcular:

This issue is not more with new version of Microblink SDK 4.0 <. So closing this issue.
