### ISSUE TITLE
Can I hide the image for flashlight button and display only text `Light`?

### ISSUE THREAD

**Issue by fatinWasta** [blinkinput/blinkinput-ios#42]
Can I hide the image for flashlight button and display only text `Light`? Please refer to the screenshot.
![blinkid](https://user-images.githubusercontent.com/14032221/50285371-0b19a380-0482-11e9-88bf-7131a96ee31b.jpg)

**Comment by jcular** [comment]
Hi @fatinWasta,

yes, but not through code. You can find the images used on the overlay in `microblink.bundle`.
You can delete them from bundle and there should be no images on the button.
Images that are used for torch button are:
```
torchon.png
torchoff.png
torchon_pressed.png
torchoff_pressed.png
torchon@2x.png
torchoff@2x.png
torchon_pressed@2x.png
torchoff_pressed@2x.png
```
Kind regards,
Jure

**Comment by fatinWasta** [comment]
@jcular ,
Yeah, thanks mate. It worked. 
Kindly close this one.

**Comment by fatinWasta** [comment]
Yeah.. that should work.. till now I can't access `image`..

**Comment by fatinWasta** [comment]
@jcular can you please update me once you discussed with the team or so.. or if you are gonna update the SDK..

**Comment by jcular** [comment]
@fatinWasta I discussed this with the rest of the team and the conclusion is that we won't be currently adding this feature since our UI comes as is, as our designers intended it to be. 
Further, currently, we don't have a close release planned for blinkinput. I would suggest that you implement your own overlay using CustomOverlayViewController, since I can't give you a specific date for the next blinkinput release.

Kind regards,
Jure

**Comment by fatinWasta** [comment]
Oh okay.. Thanks for the response..
